main:
  db:
    sqlite:
      path: "./spider.sqlite"
    leveldb:
      path: "./spider.leveldb"
    jsondb:
      path: "./spider.json"
    mysql:
      path: "mysql://spider:20090909@db:3306"
    post:
      path: "DATABASE_URL = 'postgresql://spider:20090909@db:5432/spider?schema=public"
  server:
    iciba:
      host: "http://www.iciba.com"
    douban:
      host: "https://movies.douban.com/top250"
