main:
  db:
    sqlite:
      path: "./vpsman.sqlite"
    leveldb:
      path: "./vpsman.leveldb"
    jsondb:
      path: "./vpsman.json"
    mysql:
      path: "sqlite://localhost:3306"
  server:
    iciba:
      host: "http://www.iciba.com"
