version: '3'
services:
  spider-postgres:
    image: "postgres" 
    ports: 
      - "9432:5432"
    env_file:
      - .env 
    volumes:
      - postgres-data:/var/lib/postgresql/data/ 
  chrome-headless-shell:
    image: "chromedp/headless-shell:latest"
    ports:
      - "9222:9222"
    env_file:
      - .env
    volumes:
      - ./gospinder:/gospider
      - /root/go/bin:/root/go/bin
    command:
      - /root/go/bin/gospider spider --website=douban
    links:
      - "spider-postgres"

volumes:
  postgres-data: 