version: '3'
services:
  spider-postgres:
    image: postgres
    container_name: db
    restart: always
    ports: 
      - 5432:5432
    env_file:
      - .env 
    volumes:
      - postgres-data:/var/lib/postgresql/data/ 
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    links:
      - db
    restart: always
    ports:
      - 9433:8080
  chrome-headless-shell:
    image: chromedp/headless-shell:latest
    container_name: spider
    depends_on:
      - db
    links:
      - db
    restart: always
    ports:
      - 9222:9222
    env_file:
      - .env
    volumes:
      - /root/go/bin:/root/go/bin
    command:
      - /root/go/bin/gospider spider --website=douban

volumes:
  postgres-data: 